services:
  auth:
    build: ./services/auth
    container_name: auth_container
    volumes:
      - ./common:/app/common
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file: ./services/auth/.env
    networks:
      - xm_network
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    container_name: frontend_container
    volumes:
      - ./common:/app/common
      - ./logs:/app/logs
    ports:
      - "5050:5050"
    env_file: ./services/frontend/.env
    networks:
      - xm_network
    restart: unless-stopped

networks:
  xm_network:
