name: CI/CD
#TODO
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      - 'frontend/**'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy project files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/path/to/destination/project"

    - name: Create .env files on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "${{ secrets.AUTH_ENV_FILE_CONTENT }}" > /path/to/destination/project/auth/.env
          echo "${{ secrets.FRONTEND_ENV_FILE_CONTENT }}" > /path/to/destination/project/frontend/.env

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /path/to/destination/project
          docker-compose up -d --build
